#!/usr/bin/perl -w
# -*- mode: perl; -*-
# $Id: package.pl,v 1.1 2022/06/12 16:09:55 cvsuser Exp $
# memcached package information
#
# Copyright Adam Young 2022
# All rights reserved.
#

use strict;
use warnings 'all';
use Getopt::Long;
use POSIX qw(strftime asctime);

my $output      = "memcached_package.h";
my $name        = undef;
my $version     = undef;
my $builddate   = undef;
my $tarname     = "";
my $url         = "";
my $bugreport   = "";
my $help        = 0;

Usage() if (0 == GetOptions(
		'output=s'	=> \$output,
		'name=s'	=> \$name,
		'version=s'	=> \$version,
		'date=i'	=> \$builddate,
		'tarname'	=> \$tarname,
		'url'		=> \$url,
		'bugreport'	=> \$bugreport,
		'help'		=> \$help)
			|| $help);

die "missing package name\n"
	if (! $name);

die "missing package version\n"
	if (! $version);

$builddate = strftime('%Y%m%d', localtime)
	if (! $builddate);

Generate();

sub
Generate	#()
{
	open(FILE, ">${output}") or
		die "cannot create <${output}> : $!\n";

	my ($version1, $version2, $version3, $version4) =
		split(/\./, $version);

	my $timestamp = asctime(localtime);
	chomp($timestamp);

	$version2 = 0 if (! $version2);
	$version3 = 0 if (! $version3);

	print FILE <<"EOT";
/*
 * Auto-generated by Makefile ${timestamp}
 */

/* Name of package */
#define PACKAGE                     "${name}"
#define PACKAGE_NAME                "${name}"

#define PACKAGE_VERSION_MAJOR       ${version1}
#define PACKAGE_VERSION_MINOR       ${version2}
#define PACKAGE_VERSION_REVISION    ${version3}
#define PACKAGE_BUILD_DATE          "${builddate}"

/* Define to the version of this package. */
#define PACKAGE_VERSION             "${version}"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING              "${name} - ${version}"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME             "${tarname}"

/* Define to the home page for this package. */
#define PACKAGE_URL                 "${url}"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT           "${bugreport}"
EOT
	close(FILE);
}


sub
Usage		# ([message])
{
	print "\nversion.pl @_\n\n" if (@_);
	print <<EOU;

Usage: perl version.pl [options]

Options:
    --name <name>               Package name
    --version <version>         Package version.
    --date <date>               Build date (optionaL).
    --tarname <shortname>       Symbol short name of this package.
    --url <url>                 Home page for this package.
    --bugreport <url>           Address where bug reports for this package should be sent.

EOU
	exit 3;
}

1;

#end

