#!/usr/bin/perl -w
# -*- mode: perl; -*-
# $Id: version.pl,v 1.2 2025/01/22 10:25:56 cvsuser Exp $
# liblua version information
#
# Copyright Adam Young 2022 - 2025
# All rights reserved.
#

use strict;
use warnings 'all';
use Getopt::Long;
use POSIX qw(strftime asctime);

my $output      = "version.h";
my $name        = undef;
my $version     = undef;
my $builddate   = undef;
my $tarname     = "";
my $url         = "";
my $bugreport   = "";
my $help        = 0;

Usage() if (0 == GetOptions(
		'output=s'	=> \$output,
		'name=s'	=> \$name,
		'version=s'	=> \$version,
		'date=i'	=> \$builddate,
		'tarname'	=> \$tarname,
		'url'		=> \$url,
		'bugreport'	=> \$bugreport,
		'help'		=> \$help)
			|| $help);

die "missing package name\n"
	if (! $name);

die "missing package version\n"
	if (! $version);

$builddate = strftime('%Y%m%d', localtime)
	if (! $builddate);

Generate();

sub
Generate	#()
{
	open(FILE, ">${output}") or
		die "cannot create <${output}> : $!\n";

	my ($version1, $version2, $version3, $version4) =
		split(/\./, $version);

	my $timestamp = asctime(localtime);
	chomp($timestamp);

	$version2 = 0 if (! $version2);
	$version3 = 0 if (! $version3);

	print FILE <<"EOT";
/*
 * Auto-generated by Makefile ${timestamp}
 */
#define PACKAGE_NAME        "${name}"
#define PACKAGE_STRING      "${name} - ${version}"
#define VERSION             "${version}"
#define VERSION_MAJOR       ${version1}
#define VERSION_MINOR       ${version2}
#define VERSION_REVISION    ${version3}
#define BUILD_DATE          "${builddate}"
EOT
	close(FILE);
}


sub
Usage		# ([message])
{
	print "\nversion.pl @_\n\n" if (@_);
	print <<EOU;

Usage: perl version.pl [options]

Options:
    --name <name>           Package name
    --version <version>     Package version.
    --date <date>           Build date (optionaL).

EOU
	exit 3;
}

1;

#end

